Make classes public so they could be accessed from proxies
Resolves the following in SchemaVersionLookUpActor.lookUp:

```
java.lang.BootstrapMethodError: java.lang.IllegalAccessError: tried to access class io.vlingo.xoom.schemata.infra.persistence.SchemaVersionQueryExecutor from class io.vlingo.xoom.sc
hemata.infra.persistence.SchemaVersionLookUp__Proxy
        at io.vlingo.xoom.schemata.infra.persistence.SchemaVersionLookUp__Proxy.update(SchemaVersionLookUp__Proxy.java:127)
        at io.vlingo.xoom.schemata.infra.persistence.SchemaVersionLookUpActor.lambda$null$4(SchemaVersionLookUpActor.java:96)
        at io.vlingo.xoom.common.completes.FutureCompletes$State.lambda$consumerWrapper$6(FutureCompletes.java:530)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
        at io.vlingo.xoom.common.completes.FutureCompletes$State.complete(FutureCompletes.java:343)
        at io.vlingo.xoom.common.completes.FutureCompletes.with(FutureCompletes.java:229)
        at io.vlingo.xoom.actors.CompletesEventuallyActor.with(CompletesEventuallyActor.java:21)
        at io.vlingo.xoom.actors.CompletesEventually__Proxy.lambda$with$3308d7d4$1(CompletesEventually__Proxy.java:60)
        at io.vlingo.xoom.actors.LocalMessage.internalDeliver(LocalMessage.java:121)
        at io.vlingo.xoom.actors.LocalMessage.deliver(LocalMessage.java:53)
        at io.vlingo.xoom.actors.plugin.mailbox.concurrentqueue.ConcurrentQueueMailbox.run(ConcurrentQueueMailbox.java:108)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessError: tried to access class io.vlingo.xoom.schemata.infra.persistence.SchemaVersionQueryExecutor from class io.vlingo.xoom.schemata.infra.persiste
nce.SchemaVersionLookUp__Proxy
```

Signed-off-by: Jakub Zalas <jakub@zalas.pl>